"""Derive shared API keep rules from an instrumented APK and its target's R8 reports.

Apply the output to both tested and distributed release APKs. This preserves the
same artifact under test; it does not introduce a special, less optimized test app.
Regenerate after changing instrumentation/framework dependencies and run device tests.
"""
import argparse
from pathlib import Path
import re
import struct
import zipfile


def dex_types(apk):
    references, definitions = set(), set()
    with zipfile.ZipFile(apk) as archive:
        for name in archive.namelist():
            if not re.fullmatch(r'classes\d*\.dex', name):
                continue
            data = archive.read(name)
            if not data.startswith(b'dex\n'):
                raise ValueError('Unsupported DEX: ' + name)
            integer = lambda offset: struct.unpack_from('<I', data, offset)[0]
            strings = []
            for index in range(integer(56)):
                pos = integer(integer(60) + index * 4)
                while data[pos] & 128:
                    pos += 1
                pos += 1
                strings.append(data[pos:data.index(0, pos)].decode('utf-8', errors='replace'))
            types = [strings[integer(integer(68) + index * 4)] for index in range(integer(64))]
            references.update(types)
            definitions.update(types[integer(integer(100) + index * 32)] for index in range(integer(96)))
    normalize = lambda values: {v.lstrip('[')[1:-1].replace('/', '.') for v in values if v.lstrip('[').startswith('L')}
    return normalize(references), normalize(definitions)


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('test_apk', type=Path)
parser.add_argument('mapping', type=Path)
parser.add_argument('usage', type=Path)
parser.add_argument('output', type=Path)
args = parser.parse_args()
references, definitions = dex_types(args.test_apk)
external = references - definitions
mapping = {}
for line in args.mapping.open(encoding='utf-8'):
    match = re.match(r'([^ #\s].*?) -> (.*?):\s*$', line)
    if match:
        mapping[match[1]] = match[2]
removed = {line.rstrip(':\r\n') for line in args.usage.open(encoding='utf-8')
           if line.strip() and not line.startswith((' ', '\t', '#'))}
# A merged class may appear only as a qualified method owner in mapping.txt,
# with no top-level mapping or usage entry (for example ViewTreeLifecycleOwner).
# Preserve unresolved original references as well as reverse-mapped class names.
renamed_names = set(mapping.values())
required = {original for original, renamed in mapping.items() if renamed in external} | (external - renamed_names) | (external & removed)
required = sorted(name for name in required if not name.startswith(('android.', 'java.', 'javax.', 'dalvik.', 'sun.', 'org.xml.', 'org.w3c.')))
if not required:
    raise SystemExit('No shared APIs found; refusing to replace keep rules.')
header = '''# Shared APIs referenced by the separately compiled instrumentation APK.
# Generated by tools/instrumentation-keep-rules.py from CI 110 artifacts.
# Preserve this cross-APK API boundary, including overridable methods.
# These rules are used for every release, including the distributed APK.
# R8 cannot see subclasses in the separate test APK; allowing optimization here
# can finalize methods such as JobSupport.toString and break test subclasses.
# Refresh when instrumentation or shared framework dependencies change.
'''
args.output.write_text(header + '\n'.join('-keep class ' + name + ' { *; }' for name in required) + '\n', encoding='utf-8')
print(f'Wrote {len(required)} shared API rules to {args.output}')
